Voice Conversion
SIGCOWW/L0-A pull request #5
Opened 2019-03-30 12:27 UTC by SythonUK

# 書いたぜ．
執筆者：健全ラボ土方 (3月30日（土）21時27分22秒)

2019-03-30 15:03 UTC, lrks requested changes
著者名は直してほしいですが、それ以外は問題なさそうです。

一応気になった点を挙げましたが、そのままでもapproveするつもりです。
↓は文章中に書けなかった点です。

* 画像の解像度が足りないので、印刷不鮮明になる恐れがある
* 引用の図は仕方なく、↓もそこまで深刻ではないが
  * matplotlibで書いているグラフについてはpdfで出してほしい
    * もし `plt.savefig(accuracy.png)` で書いていたら、そのまま `plt.savefig(accuracy.pdf)` でいけるはずなので
  * 作図した図もpdfか、現状の2倍は大きいサイズで書き出してほしい
    * 図をPDFに貼るとか、ペイントで2倍に拡大してほしいという意味ではありません。
    * ちなみに speech_process.png はイラストなのでpngにしてくれたのかと思いますが、一度JPEGになってしまったものをpngで保存し直すという意味ではありません。

2019-03-30 15:03 UTC, lrks commented on src/articles/vc/vc.re
> +@<author>{4月からD2の Sython;twitter:SythonUK}
著者紹介ではみ出てしまう。「4月からD2の」が肩書を意図しているなら、「Sython」との間にカンマを打ってもらうといい感じになります。`@<author>{4月からD2の, Sython;twitter:SythonUK}`

2019-03-30 15:03 UTC, lrks commented on src/articles/vc/vc.re
> +本稿の2.5節における``敵対的学習に基づくVCモデル学習(敵対的VC)の導入''で、敵対的VCの枠組みを説明します@<fn>{gans}。
`` と '' はうまく出ないので、「“」と「”」をそのまま書くしかなさそうです。(ここ以外に使われている箇所も同様です。)

Issueとして起票したので、次回からは `` '' でいけると思います。
https://github.com/SIGCOWW/desk/issues/76

2019-03-30 15:03 UTC, lrks commented on src/articles/vc/vc.re
> +: 音声発話長が長くなる
ここ4つは箇条書き `*` を使うのが妥当では？ `:` だと説明リスト要素ってのになりますね。強調もしたければ、 `* @<b>{音声発話長が長くなる}` でいけます。

2019-03-30 15:03 UTC, lrks commented on src/articles/vc/vc.re
> +風邪判定DNN @<m>{D(\bm{\cdot\})}は、入力された音声特徴量から、その話者が風邪を引いているかどうかを判定します。
修正点ではありませんが、 `@<m>{}` 命令の数式で `}` を使う際、いつからか `\}` にしなくても良くなりました。
`@<m>{D(\bm{\cdot})}` のように。

2019-03-31 07:01 UTC, lrks approved these changes
最高すぎて最高裁判所になった
まだ時間があるので、少し寝かせてまーじしますか

2019-03-31 09:16 UTC, itezaP reviewed
良さすぎて与謝野晶子になった。
大きな問題はないと思うので、よろしくお願いします。

2019-03-31 09:16 UTC, itezaP commented on src/articles/vc/vc.re
> += 一般男性音声コーパス(OJaMa)を用いた深層学習に基づく統計的声質変換入門
本文が日本語のあとの（　は「半角スペース＋半角( 」で揃えてるので、ここも揃えたほうが統一感でると思います。
（意図的にこうしてる場合はごめんなさい）

後の文章でも「”日本語”(OJaMa)」に関しては半角( の前に半角スペースを入れていないですね（統一されているので、お任せします。）

2019-03-31 09:16 UTC, itezaP commented on src/articles/vc/vc.re
> +@<img>{accuracy}に結果を示します。
Epochは学習回数であるという一言があると、より丁寧かと思います（用語がわからない人は、上記の文の
`1〜90番目の文章を学習データ、91〜100番目の`
という文章があるので、図2.26を見た際に少し混乱するかもしれません。。）（上記でEpochについて説明していたらごめんなさい）

2019-03-31 09:40 UTC, SythonUK commented
- Epoch の説明 → キャプションにつけました
- ガバガバ括弧 → 直しました（ただ，見た感じあんまり変わらない気がする）

2019-04-08 12:50 UTC, merged